### ISSUE TITLE
how to make dataset ?

### ISSUE THREAD

**Issue by luoww1992** [bbrument/RNb-NeuS#2]
how to make dataset and what is cameras_xxx.npz?

**Comment by bbrument** [comment]
Hi!
To create your dataset, start by creating a folder. Within this folder, include a folder for normal maps along with optional folders for albedo and masks. You can generate normal maps using any preferred method; for instance, [SDM-UniPS](https://github.com/satoshi-ikehata/SDM-UniPS-CVPR2023) is a suitable option that also provides reflectance maps (albedos). Regarding the cameras_xxx.npz file, it follows the same format as [IDR](https://github.com/lioryariv/idr/blob/main/DATA_CONVENTION.md).

I hope this explanation proves helpful. Please don't hesitate to reach out if you have any further questions.
