### ISSUE TITLE
Normal Angular Error.

### ISSUE THREAD

**Issue by aaryapatel007** [bbrument/RNb-NeuS#4]
Can you please share the implementation code for Figure 10 in your paper? (Code for computing the normal angular error between meshes.)

**Comment by aaryapatel007** [comment]
@bbrument Can you please help with this?

Thanks 👍🏻

**Comment by RobinBruneau** [comment]
@aaryapatel007 For MAE, we first used Blender to render normal maps based on the views provided by the calibration and then we computed a basic angular error pixel by pixel with a maximum threshold at 45°. I can add the second part of the code relative to the MAE computation fairly quickly. But if you are also interested in the Blender normal rendering, it is gonna take more time.

**Comment by aaryapatel007** [comment]
Hey @RobinBruneau, Thanks for your reply!

It will be helpful if you can share the second part of your code.

**Comment by RobinBruneau** [comment]
@aaryapatel007 , you can find my function just below : 
**normal_map_1,normal_map_2 :** HxWx3 images
**mask_1,mask_2 :** HxW images


    def MAE(normal_map_1, normal_map_2, mask_1, mask_2):
        normal_map_1 = normal_map_1 * 2.0 - 1.0
        normal_map_2 = normal_map_2 * 2.0 - 1.0
    
        mask_both = mask_1 + mask_2  # Fusion of both masks
        ind_remove = np.where(mask_1 < 0.5)  # Outside both masks
        ind_keep = np.where(mask_1 > 1.5)  # Inside both masks
        ind_bad = np.where(mask_both == 1.0)  # Only on one mask
    
        n1 = normal_map_1 / np.linalg.norm(normal_map_1, axis=2, keepdims=True)
        n2 = normal_map_2 / np.linalg.norm(normal_map_2, axis=2, keepdims=True)
        dot_n = (n1 * n2).sum(axis=2).clip(-1.0, 1.0)
        geodesic_distance = np.arccos(dot_n)
    
        MAE_score = np.copy(geodesic_distance)
        MAE_score[ind_bad[0], ind_bad[1]] = 0.0
        MAE_score[ind_remove[0], ind_remove[1]] = 0.0
        nb = len(ind_keep[0])
        MAE_mean_score = np.sum(MAE_score) / nb
    
        geodesic_distance = geodesic_distance.clip(0.0, np.pi / 4)
        geodesic_distance /= (np.pi / 4)
        geodesic_distance[ind_bad[0], ind_bad[1]] = 1.0
        MAE_image = plt.cm.jet(geodesic_distance)[:, :, :3]
        MAE_image[ind_remove[0], ind_remove[1], :] = 1
        MAE_image_crop = MAE_image[np.min(ind_keep[0]):np.max(ind_keep[0]), np.min(ind_keep[1]):np.max(ind_keep[1]), :]
    
        return MAE_score, MAE_mean_score, MAE_image, MAE_image_crop

**Comment by aaryapatel007** [comment]
Thanks @bbrument for providing the code!
I also had another doubt, how did you make the circular zoom-ins in figure 9 of the paper where you compare your method with NeuS on different number of input view.

**Comment by RobinBruneau** [comment]
@aaryapatel007 we used Gimp.

**Comment by sn-nir** [comment]
Hi @RobinBruneau, Can you please share which video editing software you used to make the mesh comparison videos?

**Comment by aaryapatel007** [comment]
Hi @RobinBruneau, Can you please share which video editing software you used to make the mesh comparison videos?

**Comment by RobinBruneau** [comment]
@aaryapatel007 We used Blender to render the frames, and then python to create the video.
