### ISSUE TITLE
Results on DTU datasets

### ISSUE THREAD

**Issue by lin-yao-yue** [bbrument/RNb-NeuS#6]
1. Have you ever tried to run code on DTU datasets, and are there corresponding results?
2. What should I do if I want to run this code on DTU datasets, and whether the DTU datasets provided in the NeuS paper are also applicable to RNb-NeuS.

**Comment by lin-yao-yue** [comment]
I actually tried to run code on DTU dataset but couldn't get the results.

**Comment by bbrument** [comment]
Our method takes normal maps as inputs and not optical images as DTU.
