### ISSUE TITLE
Train without reflectance

### ISSUE THREAD

**Issue by Terry10086** [bbrument/RNb-NeuS#7]
Thank you for your excellent work.

I wanted to ask if it would be possible to train without reflectance, given that the normal maps were generated in Blender, as I currently only have mesh information, and the normal map is totally accurate. If this isn’t feasible, could you kindly clarify what the main differences might be between training with and without reflectance in this case? Thank you very much for your guidance.

**Comment by bbrument** [comment]
Thanks for your interest @Terry10086 

Yes, you can train without reflectance with the "--no_albedo" option. The training of the albedo via a radiance fields network is then disabled and the reflectance values used in the loss function are all set to 1. Then, we only try to minimize the difference of the shading terms. You can look at the article for more details.
